### ISSUE TITLE
Link to ICCLab Puppet configuration post is broken

### ISSUE THREAD

**Issue by alansill** [tmetsch/occi-os#86]
The link in the Markdown text to the deployment using Puppet goes to an icclab tag on cloudcomp.ch and that tag link seems no longer to work.

Can an updated Puppet procedure pe posted, or the section removed?

**Comment by tmetsch** [comment]
@dizz is this still valid btw? I know puppet nova modules have support for enabled_api=... now. Is that all we need?

**Comment by dizz** [comment]
article now moved here: http://blog.zhaw.ch/icclab/automating-occi-installations/
code is here: https://github.com/stackforge/puppet-nova/blob/d87c1e8fe77bef596438fb1e8eaef48ba55c2005/manifests/api.pp#L326

**Comment by tmetsch** [comment]
cool! thanks

**Comment by tmetsch** [comment]
fixed in README
